spring:
  application:
    name: dcl-compliance-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dcl}
    username: ${SPRING_DATASOURCE_USERNAME:dcl}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  flyway:
    enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      group:
        readiness:
          include: readinessState,db

  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
